version: '3'
services:
  back:
    build: .
    ports:
     - "8080:8080"
    environment:
     - JAVA_OPTS=-Dspring.datasource.url=jdbc:mysql://mysql:3306/university
    depends_on:
     - 'mysql'
  mysql:
    image: mysql:latest
    expose:
      - '3306'
    environment:
      - MYSQL_DATABASE=university
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root